[package]
name = "resolvething"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0"
keywords = ["syncthing"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
regex = "1.11.1"
termsize = "0.1.9"
walkdir = "2.5.0"
